### ISSUE TITLE
unsubscribe atmostphere client

### ISSUE THREAD

**Issue by dhieugo** [spyboost/angular-atmosphere#1]
Hi, I would like to unsubscribe atmostphere client. Is there any correct way to do that in angularjs?

**Comment by dhieugo** [comment]
Ping

**Comment by cabelin** [comment]
I need this information too

**Comment by mukisankaran** [comment]
The unsubscribe mechanism is available as part of this fork by the Atmosphere team - https://github.com/Atmosphere/angular-atmosphere
